name: merge from test to check

on:
  workflow_dispatch:

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to check
        run: |
          git checkout check
          git merge test
          git push origin check
