name: Merge from test to check

on:
  workflow_dispatch:

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all branches and history
      - name: Configure git
        run: |
          git config --global user.name "NagasudheerM-hexaware"
          git config --global user.email "nagasudheerm@hexaware.com"
      - name: Merge test to check
        run: |
          git checkout check
          git merge test
          git push origin check
