name: merge from test to main

on:
  workflow_dispatch:

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to main
        run: |
          git checkout main 
          git merge test
          git push origin main
